from __future__ import annotations

import hashlib
import json
import re
from typing import Any

IDENTITY_ANCHOR_VERSION = 1


def _first(*values: Any):
    return next((v for v in values if v not in (None, "", "unknown", "None", "null", [], {})), None)


def fictional_age_from_range(raw: object, fallback: int | None = None) -> int:
    """Resolve the profile's current age overlay without touching core identity.

    The onboarding value may be a range (18-20), an open range (30+) or a
    localized label.  The first explicit adult age is the deterministic visual
    age anchor for the mutable profile overlay.
    """
    text = str(raw or "").translate(str.maketrans("۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩", "01234567890123456789"))
    nums = [int(x) for x in re.findall(r"\d+", text)]
    if nums:
        return max(18, nums[0])
    return max(18, int(fallback or 24))


def derive_identity_anchor(profile) -> dict:
    """Return the immutable visual identity of the fictional partner.

    Deliberately excludes age, scene, pose, clothes, lighting, camera, activity,
    temporary hair state and every request/context attribute.  Existing anchors
    are never regenerated by ordinary profile edits.
    """
    traits = dict(getattr(profile, "profile_json", None) or {})
    existing = traits.get("identity_anchor")
    if isinstance(existing, dict) and existing:
        return dict(existing)

    face_description = getattr(profile, "face_description", None)
    hair_description = getattr(profile, "hair_description", None)
    eye_description = getattr(profile, "eye_description", None)
    skin_description = getattr(profile, "skin_description", None)
    body_description = getattr(profile, "body_description", None)
    distinguishing = getattr(profile, "distinguishing_details", None)

    # Prefer atomic deterministic traits when available.  Description fallbacks
    # preserve established pre-migration identities instead of inventing a new one.
    return {
        "face_shape": _first(traits.get("face_shape"), face_description),
        "jaw": _first(traits.get("jaw"), face_description),
        "eyebrow_shape": _first(traits.get("eyebrow_shape"), face_description),
        "eye_shape": _first(traits.get("eye_shape"), eye_description),
        "eye_color": _first(traits.get("eye_color"), eye_description),
        "nose": _first(traits.get("nose"), face_description),
        "stable_feature": _first(traits.get("feature"), distinguishing),
        "hair_color": _first(traits.get("hair_color"), hair_description),
        "hair_texture": _first(traits.get("hair_texture"), hair_description),
        "skin_tone": _first(traits.get("skin_tone"), skin_description),
        "build": _first(traits.get("build"), body_description),
        "height": _first(traits.get("height"), getattr(profile, "height_impression", None)),
        "gender_presentation": _first(getattr(profile, "gender_presentation", None)),
    }


def identity_anchor_fingerprint(anchor_or_profile) -> str:
    anchor = anchor_or_profile if isinstance(anchor_or_profile, dict) else derive_identity_anchor(anchor_or_profile)
    canonical = {k: v for k, v in anchor.items() if v not in (None, "", [], {})}
    return hashlib.sha256(
        json.dumps(canonical, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def ensure_identity_anchor(profile) -> tuple[dict, str]:
    traits = dict(getattr(profile, "profile_json", None) or {})
    anchor = derive_identity_anchor(profile)
    fingerprint = identity_anchor_fingerprint(anchor)
    traits["identity_anchor"] = anchor
    traits["identity_anchor_version"] = IDENTITY_ANCHOR_VERSION
    traits["identity_anchor_fingerprint"] = fingerprint
    profile.profile_json = traits
    return anchor, fingerprint


def sync_mutable_profile_overlays(user, profile) -> dict:
    """Apply editable partner attributes without re-randomizing identity."""
    current_age = fictional_age_from_range(
        getattr(user, "partner_age_range", None),
        getattr(profile, "fictional_age", None),
    )
    profile.fictional_age = current_age
    if getattr(user, "partner_name", None):
        profile.partner_name = user.partner_name

    traits = dict(getattr(profile, "profile_json", None) or {})
    overlays = dict(traits.get("mutable_profile_overlays") or {})
    overlays.update(
        {
            "fictional_age": current_age,
            "partner_age_range": getattr(user, "partner_age_range", None),
        }
    )
    traits["mutable_profile_overlays"] = overlays
    profile.profile_json = traits
    return overlays


def identity_descriptor_from_anchor(profile) -> dict:
    anchor = derive_identity_anchor(profile)

    def joined(*values: Any):
        parts = [str(v).strip() for v in values if v not in (None, "", [], {})]
        return ", ".join(dict.fromkeys(parts)) or None

    return {
        "partner_name": _first(getattr(profile, "partner_name", None)),
        # Age is intentionally a mutable visual overlay, not part of identity fingerprint.
        "fictional_age": getattr(profile, "fictional_age", None),
        "gender_presentation": _first(anchor.get("gender_presentation"), getattr(profile, "gender_presentation", None)),
        "face": joined(anchor.get("face_shape"), anchor.get("jaw"), anchor.get("eyebrow_shape"), anchor.get("nose"), anchor.get("stable_feature")),
        # Scene-specific wet/messy/tied hair can vary; core color/texture stay anchored.
        "hair": joined(anchor.get("hair_color"), anchor.get("hair_texture")),
        "eyes": joined(anchor.get("eye_shape"), anchor.get("eye_color")),
        "skin": joined(anchor.get("skin_tone")),
        "body": joined(anchor.get("build"), anchor.get("height")),
        "distinguishing_details": joined(anchor.get("stable_feature")),
    }
