"""venice dual bots payment settings stickers

Revision ID: 0004_venice_dual_bots_payment_settings_stickers
Revises: 0003_wallet_subscription_usage
Create Date: 2026-06-13
"""
from alembic import op
import sqlalchemy as sa
revision="0004_venice_dual_bots_payment_settings_stickers"; down_revision="0003_wallet_subscription_usage"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("app_settings",sa.Column("id",sa.Integer(),nullable=False),sa.Column("key",sa.String(255),nullable=False),sa.Column("value",sa.Text(),nullable=False),sa.Column("value_type",sa.String(32),nullable=False,server_default="string"),sa.Column("description",sa.Text(),nullable=True),sa.Column("updated_by_admin_id",sa.Integer(),nullable=True),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(),nullable=False,server_default=sa.func.now()),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("key",name="uq_app_settings_key"))
    op.create_index(op.f("ix_app_settings_id"),"app_settings",["id"]); op.create_index(op.f("ix_app_settings_key"),"app_settings",["key"])
    op.create_table("payment_receipts",sa.Column("id",sa.Integer(),nullable=False),sa.Column("user_id",sa.Integer(),nullable=False),sa.Column("telegram_file_id",sa.String(512),nullable=False),sa.Column("telegram_file_type",sa.String(32),nullable=False),sa.Column("amount_toman",sa.Integer(),nullable=True),sa.Column("requested_coins",sa.Integer(),nullable=True),sa.Column("status",sa.String(32),nullable=False,server_default="pending"),sa.Column("admin_id",sa.Integer(),nullable=True),sa.Column("admin_note",sa.Text(),nullable=True),sa.Column("metadata",sa.JSON(),nullable=True),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.func.now()),sa.Column("reviewed_at",sa.DateTime(),nullable=True),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_payment_receipts_id"),"payment_receipts",["id"]); op.create_index(op.f("ix_payment_receipts_user_id"),"payment_receipts",["user_id"]); op.create_index(op.f("ix_payment_receipts_status"),"payment_receipts",["status"])
    op.create_table("sticker_packs",sa.Column("id",sa.Integer(),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("telegram_set_name",sa.String(255),nullable=False),sa.Column("description",sa.Text(),nullable=True),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(),nullable=False,server_default=sa.func.now()),sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_sticker_packs_id"),"sticker_packs",["id"]); op.create_index(op.f("ix_sticker_packs_telegram_set_name"),"sticker_packs",["telegram_set_name"])
    op.create_table("sticker_items",sa.Column("id",sa.Integer(),nullable=False),sa.Column("pack_id",sa.Integer(),nullable=True),sa.Column("telegram_file_id",sa.String(512),nullable=False),sa.Column("emoji",sa.String(32),nullable=True),sa.Column("label",sa.String(255),nullable=False),sa.Column("usage_context",sa.String(64),nullable=False),sa.Column("relationship_stage_min",sa.String(32),nullable=True),sa.Column("personality_match",sa.String(64),nullable=True),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("weight",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(),nullable=False,server_default=sa.func.now()),sa.ForeignKeyConstraint(["pack_id"],["sticker_packs.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_sticker_items_id"),"sticker_items",["id"]); op.create_index(op.f("ix_sticker_items_pack_id"),"sticker_items",["pack_id"]); op.create_index(op.f("ix_sticker_items_usage_context"),"sticker_items",["usage_context"])
    with op.batch_alter_table("daily_usage") as b: b.add_column(sa.Column("daily_stickers_sent",sa.Integer(),nullable=False,server_default="0"))
    with op.batch_alter_table("users") as b:
        b.add_column(sa.Column("last_llm_provider",sa.String(32),nullable=True)); b.add_column(sa.Column("last_llm_model",sa.String(128),nullable=True)); b.add_column(sa.Column("last_llm_status_code",sa.Integer(),nullable=True)); b.add_column(sa.Column("last_llm_error",sa.Text(),nullable=True)); b.add_column(sa.Column("last_input_tokens",sa.Integer(),nullable=True)); b.add_column(sa.Column("last_output_tokens",sa.Integer(),nullable=True)); b.add_column(sa.Column("awaiting_payment_receipt",sa.Boolean(),nullable=False,server_default=sa.false())); b.add_column(sa.Column("admin_state",sa.String(255),nullable=True))
    defaults=[("subscription.daily.price_coins","100","integer"),("subscription.weekly.price_coins","500","integer"),("subscription.monthly.price_coins","1500","integer"),("limits.free.daily_messages","30","integer"),("limits.daily.daily_messages","500","integer"),("limits.weekly.daily_messages","500","integer"),("limits.monthly.daily_messages","500","integer"),("payment.link","https://www.coffeebede.com/gotomarket","string"),("support.username","","string"),("llm.venice.model","zai-org-glm-5-1","string"),("stickers.enabled","true","boolean"),("stickers.probability","0.12","float"),("stickers.max_per_day_per_user","10","integer"),("emoji.enabled","true","boolean"),("emoji.probability","0.15","float"),("emoji.max_per_message","1","integer")]
    for k,v,t in defaults: op.execute(sa.text("INSERT INTO app_settings (key,value,value_type,created_at,updated_at) VALUES (:k,:v,:t,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").bindparams(k=k,v=v,t=t))

def downgrade():
    with op.batch_alter_table("users") as b:
        for c in ["admin_state","awaiting_payment_receipt","last_output_tokens","last_input_tokens","last_llm_error","last_llm_status_code","last_llm_model","last_llm_provider"]: b.drop_column(c)
    with op.batch_alter_table("daily_usage") as b: b.drop_column("daily_stickers_sent")
    op.drop_index(op.f("ix_sticker_items_usage_context"),table_name="sticker_items"); op.drop_index(op.f("ix_sticker_items_pack_id"),table_name="sticker_items"); op.drop_index(op.f("ix_sticker_items_id"),table_name="sticker_items"); op.drop_table("sticker_items")
    op.drop_index(op.f("ix_sticker_packs_telegram_set_name"),table_name="sticker_packs"); op.drop_index(op.f("ix_sticker_packs_id"),table_name="sticker_packs"); op.drop_table("sticker_packs")
    op.drop_index(op.f("ix_payment_receipts_status"),table_name="payment_receipts"); op.drop_index(op.f("ix_payment_receipts_user_id"),table_name="payment_receipts"); op.drop_index(op.f("ix_payment_receipts_id"),table_name="payment_receipts"); op.drop_table("payment_receipts")
    op.drop_index(op.f("ix_app_settings_key"),table_name="app_settings"); op.drop_index(op.f("ix_app_settings_id"),table_name="app_settings"); op.drop_table("app_settings")
