from datetime import datetime
from sqlalchemy import BigInteger, DateTime, ForeignKey, Integer, LargeBinary, JSON, String, Text, UniqueConstraint, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base

class PartnerVisualProfile(Base):
    __tablename__ = 'partner_visual_profiles'
    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey('users.id'), unique=True, nullable=False, index=True)
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    partner_name: Mapped[str | None] = mapped_column(String(64))
    fictional_age: Mapped[int] = mapped_column(Integer, default=24, nullable=False)
    gender_presentation: Mapped[str | None] = mapped_column(String(64))
    ethnicity_or_regional_style: Mapped[str | None] = mapped_column(Text)
    face_description: Mapped[str | None] = mapped_column(Text)
    hair_description: Mapped[str | None] = mapped_column(Text)
    eye_description: Mapped[str | None] = mapped_column(Text)
    skin_description: Mapped[str | None] = mapped_column(Text)
    body_description: Mapped[str | None] = mapped_column(Text)
    height_impression: Mapped[str | None] = mapped_column(Text)
    default_style: Mapped[str | None] = mapped_column(Text)
    distinguishing_details: Mapped[str | None] = mapped_column(Text)
    default_city: Mapped[str | None] = mapped_column(String(64))
    base_seed: Mapped[int] = mapped_column(Integer, default=-1, nullable=False)
    profile_json: Mapped[dict | None] = mapped_column(JSON)
    source: Mapped[str] = mapped_column(String(32), default='derived', nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

class ImageGenerationJob(Base):
    __tablename__ = 'image_generation_jobs'
    id: Mapped[int] = mapped_column(primary_key=True)
    idempotency_key: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    correlation_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    user_id: Mapped[int] = mapped_column(ForeignKey('users.id'), nullable=False, index=True)
    chat_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    source_telegram_message_id: Mapped[int | None] = mapped_column(BigInteger)
    addon_key: Mapped[str] = mapped_column(String(64), default='image_generation_unlock', nullable=False)
    status: Mapped[str] = mapped_column(String(32), default='queued', nullable=False, index=True)
    content_mode: Mapped[str] = mapped_column(String(32), default='normal', nullable=False)
    user_request: Mapped[str | None] = mapped_column(Text)
    prompt: Mapped[str | None] = mapped_column(Text)
    negative_prompt: Mapped[str | None] = mapped_column(Text)
    prompt_engine_version: Mapped[str | None] = mapped_column(String(64))
    visual_profile_version: Mapped[int | None] = mapped_column(Integer)
    provider: Mapped[str] = mapped_column(String(32), default='venice', nullable=False)
    model: Mapped[str] = mapped_column(String(128), default='krea-2-turbo', nullable=False)
    width: Mapped[int] = mapped_column(Integer, default=1024, nullable=False)
    height: Mapped[int] = mapped_column(Integer, default=1280, nullable=False)
    steps: Mapped[int] = mapped_column(Integer, default=45, nullable=False)
    cfg_scale: Mapped[int] = mapped_column(Integer, default=4, nullable=False)
    seed: Mapped[int] = mapped_column(Integer, default=-1, nullable=False)
    attempt_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    max_attempts: Mapped[int] = mapped_column(Integer, default=3, nullable=False)
    scheduled_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    locked_at: Mapped[datetime | None] = mapped_column(DateTime)
    lock_expires_at: Mapped[datetime | None] = mapped_column(DateTime, index=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime)
    generated_at: Mapped[datetime | None] = mapped_column(DateTime)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime)
    failed_at: Mapped[datetime | None] = mapped_column(DateTime)
    provider_request_id: Mapped[str | None] = mapped_column(String(255))
    usage_charge_id: Mapped[int | None] = mapped_column(ForeignKey('usage_charges.id'), index=True)
    telegram_message_id: Mapped[int | None] = mapped_column(BigInteger)
    error_code: Mapped[str | None] = mapped_column(String(64))
    error_message: Mapped[str | None] = mapped_column(Text)
    metadata_json: Mapped[dict | None] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    artifacts = relationship('ImageGenerationArtifact', back_populates='job', cascade='all, delete-orphan')

class ImageGenerationArtifact(Base):
    __tablename__ = 'image_generation_artifacts'
    id: Mapped[int] = mapped_column(primary_key=True)
    job_id: Mapped[int] = mapped_column(ForeignKey('image_generation_jobs.id'), unique=True, nullable=False, index=True)
    mime_type: Mapped[str] = mapped_column(String(64), nullable=False)
    checksum: Mapped[str] = mapped_column(String(128), nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False)
    image_bytes: Mapped[bytes | None] = mapped_column(LargeBinary)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    cleared_at: Mapped[datetime | None] = mapped_column(DateTime)
    job = relationship('ImageGenerationJob', back_populates='artifacts')

class ImageGenerationFeedback(Base):
    __tablename__ = 'image_generation_feedback'
    __table_args__ = (UniqueConstraint('job_id','user_id', name='uq_image_feedback_job_user'),)
    id: Mapped[int] = mapped_column(primary_key=True)
    job_id: Mapped[int] = mapped_column(ForeignKey('image_generation_jobs.id'), nullable=False, index=True)
    user_id: Mapped[int] = mapped_column(ForeignKey('users.id'), nullable=False, index=True)
    rating: Mapped[str] = mapped_column(String(16), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
